name: Generate Contribution Art

on:
  workflow_dispatch:
  schedule:
    # Runs every Sunday at midnight UTC
    - cron: "1 0 * * 0"

jobs:
  generate-art:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Contribution Art Generator
      run: |
        python -m pip install --upgrade pip
        pip install github-contributions

    - name: Generate Contribution Art
      env:
        REPO: ${{ github.repository }}
        USERNAME: ${{ github.repository_owner }}
      run: |
        github_contributions --username "${USERNAME}" \
          --message "Generating art for RVORINE" \
          --art "RVORINE" \
          --repo "${REPO}" \
          --commit-date-start "2025-01-01" \
          --commit-date-end "2025-12-31"

    - name: Push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git push origin main
