name: Generate Contribution Art

on:
  workflow_dispatch:
  schedule:
    # Runs every Sunday at midnight UTC
    - cron: "1 0 * * 0"

jobs:
  generate-art:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Generate Art
        run: |
          git config user.name "rvorine"
          git config user.email "ravikant.vishwakarma0@gmail.com"
          python generate_art.py

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "rvorine"
          git config user.email "ravikant.vishwakarma0@gmail.com"
          git push origin main
